---
driver_plugin: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04-chef-12
    driver:
      box: bento/ubuntu-16.04
    provisioner:
      require_chef_omnibus: 12
  - name: ubuntu-16.04-chef-13
    driver:
      box: bento/ubuntu-16.04
    provisioner:
      require_chef_omnibus: 13
  - name: centos-7.3-chef-12
    driver:
      box: bento/centos-7.3
    provisioner:
      require_chef_omnibus: 12
  - name: centos-7.3-chef-13
    driver:
      box: bento/centos-7.3
    provisioner:
      require_chef_omnibus: 13

suites:
  - name: default_composer
    run_list:
      - recipe[phpcs::default]
    attributes:
      phpcs:
        install_method: composer
  - name: coding-standard-in-subdir
    run_list:
      - recipe[phpcs::default]
      - recipe[phpcs::coding_standard]
    attributes:
      phpcs:
        install_method: composer
        coding_standards:
          Symfony:
            repository: git://github.com/djoos/Symfony-coding-standard.git
            reference: master
            subdirectory: Symfony
