---
driver_plugin: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.19.36

platforms:
  - name: ubuntu-16.04

suites:
  - name: default_composer
    run_list:
      - recipe[phpcs::default]
    attributes:
      phpcs:
        install_method: composer
  - name: coding-standard-in-subdir
    run_list:
      - recipe[phpcs::default]
      - recipe[phpcs::coding_standard]
    attributes:
      phpcs:
        install_method: composer
        coding_standards:
          Symfony:
            repository: git://github.com/djoos/Symfony-coding-standard.git
            reference: master
            subdirectory: Symfony
