---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]

suites:
  - name: default_composer
    run_list:
      - recipe[phpcs::default]
    attributes:
      phpcs:
        install_method: composer
  - name: coding-standard-in-subdir
    run_list:
      - recipe[phpcs::default]
      - recipe[phpcs::coding_standard]
    attributes:
      phpcs:
        install_method: composer
        coding_standards:
          Symfony2:
            repository: git://github.com/djoos/Symfony2-coding-standard.git
            reference: master
            subdirectory: Symfony2
