---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-14.04
    driver_config:
      box: opscode-ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[phpcs::default]
    attributes:
      phpcs:
        install_method: composer
  - name: coding-standard-in-subdir
    run_list:
      - recipe[phpcs::default]
      - recipe[phpcs::coding_standard]
    attributes:
      phpcs:
        install_method: composer
        coding_standards:
          Symfony2:
            repository: git://github.com/escapestudios/Symfony2-coding-standard.git
            reference: master
            subdirectory: Symfony2
